CREATE TABLE `TPEX`.`DailyPrice` (
    `Date` DATE NOT NULL,
    `Code` VARCHAR(10) NOT NULL,
    `Close` DECIMAL(7,2) ,
    `Change` DECIMAL(7,2) ,
    `Open` DECIMAL(7,2) ,
    `High` DECIMAL(7,2) ,
    `Low` DECIMAL(7,2),
    `TradeVolume` INT,
    `TradeAmount` BIGINT,
    `NumberOfTransactions` INT,
    `LastBestBidPrice` DECIMAL(7,2),
    `LastBidVolume` DECIMAL(9,2),
    `LastBestAskPrice` DECIMAL(7,2),
    `LastBestAskVolume` INT,
    `IssuedShares` BIGINT,
    `NextDayUpLimitPrice` DECIMAL(7,2),
    `NextDayDownLimitPrice` DECIMAL(7,2),
    PRIMARY KEY (`Date`, `Code`)
)